server:
  port: 8761

spring:
  security:
    user:
      name: admin
      password: psw
  application:
    name: daily-discovery-service



eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:psw@localhost:8761/eureka/