spring:
    application:
        name: cloud-config-service

    cloud:
        config:
            server:
                git:
                    uri: https://github.com/alexey8686/root-daily-planer
                    search-paths:
                        - '*service'




server:
    port: 8888
logging:
    level:
        root: INFO

management:
    endpoints:
        web:
            exposure:
                include: refresh

